version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app  
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=fastapi_db
      - PYTHONPATH=/app 
    command: >
      sh -c "
      /wait-for-it.sh mariadb:3306 -- 
      && python populate_data.py 
      && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
      "

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fastapi_db
    ports:
      - "3306:3306"  
    volumes:
      - ./data:/var/lib/mysql  
